# Generated by Django 2.2.1 on 2019-05-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbr', models.CharField(max_length=5, unique=True)),
                ('compclass', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCapstoneApp.School')),
            ],
        ),
        migrations.CreateModel(
            name='PrelimRaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districttime', models.FloatField()),
                ('districtplace', models.IntegerField()),
                ('heat', models.IntegerField()),
                ('athleteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCapstoneApp.Athletes')),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCapstoneApp.Events')),
            ],
        ),
        migrations.CreateModel(
            name='FinalRaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prelimtime', models.FloatField()),
                ('prelimplace', models.IntegerField()),
                ('athleteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCapstoneApp.Athletes')),
                ('prelimid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCapstoneApp.PrelimRaces')),
            ],
        ),
        migrations.AddField(
            model_name='athletes',
            name='schoolid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCapstoneApp.School'),
        ),
    ]
